### ISSUE TITLE
whats this

### ISSUE THREAD

**Issue by its-pablo** [NanderTGA/msgroom-orm#1]
is this a server for msgroom? I was going to make one at 
https://gitlab.com/its-pablo/msgroom-server
@NanderTGA are you still working on this an stuff

**Comment by NanderTGA** [comment]
It's an abandoned msgroom client. I originally wrote the socket.io events typings I gave to you for this project. It has a more object oriented approach and is on npm IIRC under the name "msgroom". The goal was to also make a server yes.

**Comment by its-pablo** [comment]
ahhhhhh a monorepo for a client and a server!! very nice
I might abandon my server and client and just contribute to this one tbh
