### ISSUE TITLE
Don't have bots respond to themselves

### ISSUE THREAD

**Issue by mybearworld** [NanderTGA/msgroom-orm#34]
With a `say` command, there's always the issue of someone doing `!say !say !say !say !say !say !say !say !say` and rate limiting the bot. This would be solved if the bot automatically didn't respond to itself.

A problem: It would need to somehow know if it is itself, or just its creator with the same ID.

**Comment by NanderTGA** [comment]
I have thought of this before, and there is a potential solution, but it would be a bit, hacky, to say the least.

The way it would work is to block the bots own sessionID, but we don't know it. This is where the hacky part comes in.
The solution would be to send a welcome message (developers can customize it) and to listen for new messages and try to tell our welcome message apart.

This relies on the fact that nobody with the same ID will send the exact same message right before we send ours.
A race condition is *technically possible*, but unlikely.

I have suggested ctrlz to also tell the user their session ID, but he has been ghosting me for 20+ days.
