### ISSUE TITLE
Aliases proposal

### ISSUE THREAD

**Issue by NanderTGA** [NanderTGA/msgroom-orm#35]
```js
// let's say we want to define pong, an alias for ping
client.commands.pong = {
  alias: true,
  original: client.commands.ping,
  originalName: "ping",
}
```

```js
// let's say we want to define pong, an alias for otherCommand.ping
client.commands.pong = {
  alias: true,
  original: client.commands.otherCommand.ping,
  originalName: "otherCommand.ping",
}
```
Like this we can hide aliases from the help command.

**Comment by NanderTGA** [comment]
Proposal 2:
Add an aliases property to the Command type.
Requires iterating over all the commands though.

**Comment by mybearworld** [comment]
These would be quite helpful for toB's Hangman command, e.g. being able to use `%hangman g` instead of `%hangman guess` (or if #43 is implemented, `%hm g`).

**Comment by NanderTGA** [comment]
plan is to implement both, but I encountered #48

**Comment by NanderTGA** [comment]
Aliases have been implemented like this:
say there's an alias `hangman g` for `hangman guess`, you'd write it like this:
```js
client.commands.hangman.subcommands.guess = {
  // other command stuff here...
  aliases: [
    [ "hangman", "g" ]
  ]
}
```
I have found this to be the best way to achieve this, especially considering when arguments which have spaces in them could become a thing in the future, see #60 about that.
