### ISSUE TITLE
Change datatype of commandPrefixes to Set

### ISSUE THREAD

**Issue by NanderTGA** [NanderTGA/msgroom-orm#42]
A Set makes more sense here. No duplicates + easier to remove specific prefixes.

**Comment by NanderTGA** [comment]
I'm also taking the opportunity here to provide the ability disable the command system completely.
If you want to disable the command system, set the main prefix to an empty string.

**Comment by mybearworld** [comment]
Thank you, msgroom-js-semantic-release, this is *really* helpful to know

**Comment by NanderTGA** [comment]
I'm sorry if that message was annoying, I didn't know it would comment on every issue and PR closed in the last eight months. It does explain why it took around ten minutes to run though.
But I still think it can be pretty useful in the future.

**Comment by mybearworld** [comment]
It's fine - it was just a bit surprising.
(Also, merging 2.0 while msgroom is down is kind of funny :P)
