### ISSUE TITLE
Metadata for commandMaps

### ISSUE THREAD

**Issue by NanderTGA** [NanderTGA/msgroom-orm#43]
Right now a `commandMap` cannot have a description of its own.
Solution?
```js
client.commands.thing = {
  undefined: { handler: ... },
  subcommand: { handler: ... },
}
```
Will turn into
```js
client.commands.thing = {
  description: ...,
  aliases: [...],
  handler: () => "some thing",
  subcommands: {
    undefined: { handler: ... },
    subcommand: { handler: ... },
  }
}
```
I don't know for sure if this is a proper solution though.
Any feedback is greatly appreciated!

**Comment by mybearworld** [comment]
This might work:
```ts
client.commands.thing = {
  description: ...,
  aliases: [ ... ],
  undefined: { handler: ... },
  subcommand: { handler: ... },
}
```
But then `description` and `aliases` couldn't be a subcommand. I don't think that would be too bad, though.

**Comment by NanderTGA** [comment]
On one side yes, but what if we add more metadata in the future? It would mean a breaking change every time, which we should avoid as much as possible.

**Comment by mybearworld** [comment]
True. The commandMap would make the most sense, then.

**Comment by NanderTGA** [comment]
I think we should also give this a property named handler
If we then call `!thing`, it will call this new property instead of commandMap.undefined

**Comment by NanderTGA** [comment]
Let's also rename commandMap to subcommands
