### ISSUE TITLE
Pages for the help command

### ISSUE THREAD

**Issue by NanderTGA** [NanderTGA/msgroom-orm#44]
In case it gets too long
Syntax: `!help <page>`

**Comment by mybearworld** [comment]
I think it should definitely only do that if it's actually required - the way SoBot does this is weird, for example, as it just cuts off at 5 commands, even though that's not necessary.

**Comment by NanderTGA** [comment]
Yeah, a simple if statement should do the trick. (limit of messages is 2048 characters)

**Comment by mybearworld** [comment]
Bump - doing `%help` with toB fills the whole screen. It's not ideal.

**Comment by NanderTGA** [comment]
Oh.
How about we add some limit on how much commands to show on one page?
Any suggestions on how much the default should be?

**Comment by NanderTGA** [comment]
@mybearworld any suggestions on how much the limit should be?

**Comment by mybearworld** [comment]
10 would work pretty well for toB:

![toB sending a help message with only 10 of its option, so it's not that long](https://github.com/NanderTGA/msgroom-orm/assets/130385691/5dcffe09-4ce6-4927-ab22-8fd78df63276)
