### ISSUE TITLE
Allow any capitalization for commands

### ISSUE THREAD

**Issue by mybearworld** [NanderTGA/msgroom-orm#46]
If a command `ask` gets registered, then `%ask something` and `%ASK something` and `%aSK something` should also lead to that command. There have been some cases of people using `%ASK A CAPITALIZED QUESTION`, so I think it makes sense.

**Comment by NanderTGA** [comment]
This is indeed not intentional, see #36.

**Comment by NanderTGA** [comment]
no problem
