### ISSUE TITLE
We need a way to put commands and events in other files

### ISSUE THREAD

**Issue by NanderTGA** [NanderTGA/msgroom-orm#6]
I managed to implement putting commands in other files in yabluzo, but it's far from ideal and other people are on their own.

**Comment by NanderTGA** [comment]
I have no idea on how to design this. Any input and suggestions from others is appreciated

**Comment by NanderTGA** [comment]
I got an idea: we provide a function that loads commands from a specific file.
This function uses `import()` to get the default export which should be a function that we pass the instance of client as the only argument.
Then the function should return an object satisfying `CommandHandlerMap`, which will have all of its properties assigned to `client.commands`

**Comment by NanderTGA** [comment]
I'm also gonna implement a function to load all commands from a directory

**Comment by NanderTGA** [comment]
This feature works perfectly really. I do have one thing I want to add though:
I don't want to bot to crash because of one module being faulty.
What do we do instead? Implement a warning system, sending a message when the help command is ran.
Like this we can tell people some module is faulty (provide the filename perhaps? do you agree with this @mybearworld?)

**Comment by NanderTGA** [comment]
I got an issue once with yabluzo where some module caused the entire thing to just not do anything at all. I had to delete every module one by one and update compiled js files over ftp to tell users I had to disable a part of yabluzo.
I don't want anyone to have to deal with that.
How about we add a verbose mode which can also be triggered by setting an environment variable?

**Comment by mybearworld** [comment]
> sending a message when the help command is ran.

Wouldn't the console be a better place here? The bot creator would see it instantly, rather than being confused for a bit, and then remembering they can run the help command to check for invalid modules.

**Comment by NanderTGA** [comment]
I'd do both incase the developer doesn't see one of the two.

**Comment by NanderTGA** [comment]
It seems that the types are not really working that well.
I'm talking about these:
```ts
export type ModuleInitializeFunctionReturnType = Promise<CommandWithName | CommandMap | void> | CommandWithName | CommandMap | void;
export type ModuleInitializeFunction = (client: Client) => ModuleInitializeFunctionReturnType;
```
The first one causes problems with the autocomplete (see the screenshots):
![afbeelding](https://github.com/NanderTGA/msgroom-orm/assets/65074195/8a43bc12-403d-4e5c-9106-852ecd2a2b68)
![afbeelding](https://github.com/NanderTGA/msgroom-orm/assets/65074195/2b679bc9-a774-4848-a7e2-ab278cf09bf6)
![afbeelding](https://github.com/NanderTGA/msgroom-orm/assets/65074195/ad9e2107-aa1a-49e1-a1c2-2fe9b176871e)
The problems come from the support for asynchronous initialize functions, which is causing all kinds of weird stuff with typescript like this.

I'm trying to come up with a way to fix this, without removing support for asynchronous intialize functions.
If you're using this feature, ignore the type errors for now, as the library still handles the output of these functions correctly.

**Comment by NanderTGA** [comment]
I think I should be able to fix the type *errors* but not the autocomplete as it's *technically* corrrect.
You'll have to ignore the promise-related stuff

**Comment by NanderTGA** [comment]
I found a solution:
`ModuleInitializeFunction` is now either a function that takes the `client` argument and returns `ModuleInitializeFunctionReturnType`, or a function that also takes the `client` argument, but returns `Promise<ModuleInitializeFunctionReturnType>`.

To get rid of the Promise-related stuff, put after your return object `satisfies CommandWithName`, like this:
![afbeelding](https://github.com/NanderTGA/msgroom-orm/assets/65074195/6238ecda-aa54-452d-aaf4-ca2f174457a2)

These changes will be committed soon.
