### ISSUE TITLE
Adding API keys

### ISSUE THREAD

**Issue by miki1513** [NanderTGA/msgroom-orm#90]
You should add bot API keys. Example: import Client from "msgroom";

const client = new Client("TestBot", "APIKey", [ "!" ]);
await client.connect();

**Comment by NanderTGA** [comment]
This feature already exists, it works like this:
```js
const client = new Client("[!] TestBot", "!", {
    apikey: "api key here"
});
```
You can get an apikey from ctrlz.
One problem though: it hasn't been implemented in the msgroom server.
We have no idea how this stuff would even work and what the difference would be between using an apikey and not using one.
Ctrlz still has to figure this out and probably isn't going to anytime soon.

You might also want to look into code formatting in markdown 😃

**Comment by NanderTGA** [comment]
Also if you're only using one prefix, youc an turn `[ "!" ]` into `"!"`

**Comment by miki1513** [comment]
Oh, ok
